VERSION=${shell head -1 debian.apt-builder/changelog | cut -d'(' -f2 | cut -d'-' -f1}

apt-builder-fetch:
	ln -nsf debian.apt-builder debian

apt-builder-deps:
	# noop

apt-builder-build:
	ln -nsf debian.build debian
	ant -Dversion=$(VERSION) debian
	mv target/*.changes target/*.deb ..
